### ISSUE TITLE
Kjempebra initiativ 💯🎉

### ISSUE THREAD

**Issue by Starefossen** [bergenkommune/designsystem#1]
Kjempebra initiativ!!!! 🎉😄✨ Det hadde vært kult å høre mer om hvilke planer Bergen Kommune har mhp. opensourcing av ulike deler av sin software stack.

Ta gjerne en kikk på [Repo → Insights → Community](https://github.com/bergenkommune/designsystem/community) som inneholder gode tips og hint for hvert enkelt repository om best practices for open source prosjekter på GitHub. Dette innebærer ting som f.eks. README, lisens, code of conduct, contributing, osv.

Stå på, og ta gjerne kontakt om dere ønsker å høre mer om livet som open source maintainer! 😄

**Comment by danielstrietzel** [comment]
Så bra at du syns det! :+1: Og jeg er helt enig at det kunne legges ut enda mer!  :sweat_smile:

Tilbakemeldingen din er allerede sendt videre! Også takk for tips!  :ok_hand:
